import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { SessionProvider, getSession } from "next-auth/react";
import ReactQueryProvider from "@/providers/reactQuery.provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">
      {/* <SessionProvider session={session}> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer />
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
      {/* </SessionProvider> */}
    </html>
  );
}

// Fetch session data
RootLayout.getInitialProps = async ({ ctx }) => {
  const session = await getSession(ctx);
  return {
    session: session ? JSON.parse(JSON.stringify(session)) : null, // Ensure session is a plain object
  };
};
